title: Design Knowledge Base
description: An open-source design documentation repository to provide a central location for design education.
baseurl: ""


google_analytics: UA-8657893-7
plugins:
  - jekyll-feed
  - jekyll-sitemap