title: Design Knowledge Base
description: An open-source design documentation repository to provide a central location for design education.
baseurl: ""


plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - PRODUCT.md
  - DESIGN.md
  - DESIGN.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - "Design Knowledge Base Styles.sketch"
  - "Design Knowledge Base Styles.xd"